/** A video format/stream option. */
export interface VideoFormat {
  itag: number;
  url: string;
  mimeType: string;
  codec: string;
  container: string;
  quality: string;
  qualityLabel: string;
  width: number | null;
  height: number | null;
  fps: number | null;
  bitrate: number | null;
  audioBitrate: number | null;
  audioCodec: string | null;
  videoCodec: string | null;
  hasAudio: boolean;
  hasVideo: boolean;
  contentLength: number | null;
  isLive: boolean;
}

/** A video/playlist thumbnail. */
export interface Thumbnail {
  url: string;
  width: number;
  height: number;
}

/** A video chapter marker. */
export interface Chapter {
  title: string;
  startTime: number;
  endTime: number;
}

/** A subtitle/caption track. */
export interface SubtitleTrack {
  language: string;
  languageCode: string;
  url: string;
  isAutoGenerated: boolean;
}

/** Complete video metadata and available formats. */
export interface VideoInfo {
  id: string;
  url: string;
  title: string;
  description: string;
  duration: number;
  thumbnails: Thumbnail[];
  channel: {
    id: string;
    name: string;
    url: string;
    subscribers: string | null;
  };
  viewCount: number;
  uploadDate: string;
  category: string;
  tags: string[];
  isLive: boolean;
  isPrivate: boolean;
  formats: VideoFormat[];
  subtitles: SubtitleTrack[];
  chapters: Chapter[];
}

/** A single video within a playlist. */
export interface PlaylistItem {
  id: string;
  title: string;
  duration: number;
  thumbnail: Thumbnail | null;
  channel: { name: string; id: string };
  index: number;
}

/** Playlist metadata and its videos. */
export interface PlaylistInfo {
  id: string;
  url: string;
  title: string;
  description: string;
  channel: { name: string; id: string; url: string };
  videoCount: number;
  thumbnails: Thumbnail[];
  videos: PlaylistItem[];
}

/** A single YouTube search result. */
export interface SearchResult {
  type: 'video' | 'playlist' | 'channel';
  id: string;
  title: string;
  url: string;
  thumbnail: Thumbnail | null;
  duration?: number;
  viewCount?: number;
  uploadDate?: string;
  channel?: { name: string; id: string };
  videoCount?: number;
  subscribers?: string;
}

/** Options for downloading a video. */
export interface DownloadOptions {
  quality?: 'highest' | 'lowest' | 'highestaudio' | 'lowestaudio' | 'highestvideo' | 'lowestvideo' | number;
  format?: 'mp4' | 'webm' | 'mp3' | 'm4a' | 'opus' | 'flac' | 'wav';
  outputDir?: string;
  filename?: string;
  overwrite?: boolean;
}

/** Options for downloading audio from a video. */
export interface AudioDownloadOptions extends DownloadOptions {
  audioBitrate?: '64kbps' | '128kbps' | '192kbps' | '256kbps' | '320kbps';
}

/** Options for downloading a playlist. */
export interface PlaylistDownloadOptions extends DownloadOptions {
  concurrency?: number;
  startIndex?: number;
  endIndex?: number;
  onVideoStart?: (video: PlaylistItem, index: number) => void;
  onVideoComplete?: (video: PlaylistItem, index: number, filePath: string) => void;
  onVideoError?: (video: PlaylistItem, index: number, error: Error) => void;
}

/** Real-time download progress data. */
export interface DownloadProgress {
  percent: number;
  downloaded: number;
  total: number;
  speed: number;
  eta: number;
}

/** Result of a completed download. */
export interface DownloadResult {
  filePath: string;
  title: string;
  duration: number;
  fileSize: number;
  format: string;
  quality: string;
}

/** Result of a completed playlist download. */
export interface PlaylistDownloadResult {
  playlistTitle: string;
  totalVideos: number;
  completed: number;
  failed: number;
  results: Array<{
    video: PlaylistItem;
    result: DownloadResult | null;
    error: Error | null;
  }>;
}

/** Filter options for selecting formats. */
export interface FormatFilter {
  hasAudio?: boolean;
  hasVideo?: boolean;
  container?: string;
  minHeight?: number;
  maxHeight?: number;
  minBitrate?: number;
  maxBitrate?: number;
}

/** Configuration options for the YtdlPlus client. */
export interface YtdlPlusOptions {
  cookies?: string;
  proxy?: string;
  userAgent?: string;
  lang?: string;
  geo?: string;
}

/** Event handler signatures for download events. */
export interface DownloadEvents {
  progress: (progress: DownloadProgress) => void;
  start: (info: { title: string; format: VideoFormat }) => void;
  end: (result: DownloadResult) => void;
  error: (error: Error) => void;
}
