import { getInnertube } from './client';
import type {
  VideoInfo,
  VideoFormat,
  Thumbnail,
  SubtitleTrack,
  Chapter,
  PlaylistInfo,
  PlaylistItem,
  YtdlPlusOptions,
} from '../types';
import { extractVideoId, extractPlaylistId } from '../utils/validate';

function mapThumbnails(thumbnails: Array<{ url: string; width: number; height: number }>): Thumbnail[] {
  return thumbnails.map((t) => ({
    url: t.url,
    width: t.width,
    height: t.height,
  }));
}

function mapFormats(formats: Array<Record<string, unknown>>): VideoFormat[] {
  return formats.map((f) => ({
    itag: (f.itag as number) ?? 0,
    url: (f.decipher_url as string) ?? (f.url as string) ?? '',
    mimeType: (f.mime_type as string) ?? '',
    codec: (f.codecs as string) ?? '',
    container: extractContainer((f.mime_type as string) ?? ''),
    quality: (f.quality as string) ?? '',
    qualityLabel: (f.quality_label as string) ?? (f.quality as string) ?? '',
    width: (f.width as number) ?? null,
    height: (f.height as number) ?? null,
    fps: (f.fps as number) ?? null,
    bitrate: (f.bitrate as number) ?? null,
    audioBitrate: (f.average_bitrate as number) ?? null,
    audioCodec: extractAudioCodec((f.mime_type as string) ?? '', (f.codecs as string) ?? ''),
    videoCodec: extractVideoCodec((f.mime_type as string) ?? '', (f.codecs as string) ?? ''),
    hasAudio: (f.has_audio as boolean) ?? false,
    hasVideo: (f.has_video as boolean) ?? false,
    contentLength: f.content_length ? Number(f.content_length) : null,
    isLive: (f.is_live as boolean) ?? false,
  }));
}

function extractContainer(mimeType: string): string {
  const match = mimeType.match(/\/([\w]+)/);
  return match?.[1] ?? 'unknown';
}

function extractAudioCodec(mimeType: string, codecs: string): string | null {
  if (!mimeType.startsWith('audio/') && !codecs) return null;
  if (mimeType.startsWith('audio/')) return codecs || null;
  const parts = codecs.split(',').map((c) => c.trim());
  return parts.length > 1 ? parts[1] ?? null : null;
}

function extractVideoCodec(mimeType: string, codecs: string): string | null {
  if (!mimeType.startsWith('video/')) return null;
  const parts = codecs.split(',').map((c) => c.trim());
  return parts[0] ?? null;
}

export async function getVideoInfo(urlOrId: string, options?: YtdlPlusOptions): Promise<VideoInfo> {
  const innertube = await getInnertube(options);
  const videoId = extractVideoId(urlOrId) ?? urlOrId;

  const info = await innertube.getBasicInfo(videoId);
  const details = info.basic_info;

  const streamingData = info.streaming_data;
  const allFormats: Array<Record<string, unknown>> = [];
  if (streamingData) {
    if (streamingData.formats) {
      allFormats.push(...(streamingData.formats as unknown as Array<Record<string, unknown>>));
    }
    if (streamingData.adaptive_formats) {
      allFormats.push(...(streamingData.adaptive_formats as unknown as Array<Record<string, unknown>>));
    }
  }

  const captions = info.captions;
  const subtitles: SubtitleTrack[] = [];
  if (captions?.caption_tracks) {
    for (const track of captions.caption_tracks) {
      subtitles.push({
        language: track.name?.text ?? track.language_code ?? '',
        languageCode: track.language_code ?? '',
        url: track.base_url ?? '',
        isAutoGenerated: track.kind === 'asr',
      });
    }
  }

  const chapters: Chapter[] = [];
  try {
    const infoAny = info as unknown as Record<string, unknown>;
    const playerOverlays = infoAny['player_overlays'] as Record<string, unknown> | undefined;
    if (playerOverlays) {
      const decoratedPlayerBar = playerOverlays['decorated_player_bar'] as Record<string, unknown> | undefined;
      if (decoratedPlayerBar) {
        const markerMap = decoratedPlayerBar['player_bar'] as Record<string, unknown> | undefined;
        const markers = markerMap?.['markers_map'] as Array<Record<string, unknown>> | undefined;
        if (markers) {
          for (const entry of markers) {
            const markersList = entry['value'] as Record<string, unknown> | undefined;
            const chapterList = markersList?.['chapters'] as Array<Record<string, unknown>> | undefined;
            if (chapterList) {
              for (const ch of chapterList) {
                const chapterRenderer = ch['chapter_renderer'] as Record<string, unknown> | undefined;
                if (chapterRenderer) {
                  chapters.push({
                    title: ((chapterRenderer['title'] as Record<string, unknown>)?.['simple_text'] as string) ?? '',
                    startTime: (chapterRenderer['time_range_start_millis'] as number ?? 0) / 1000,
                    endTime: 0,
                  });
                }
              }
            }
          }
          for (let i = 0; i < chapters.length; i++) {
            const nextChapter = chapters[i + 1];
            const currentChapter = chapters[i];
            if (currentChapter) {
              currentChapter.endTime = nextChapter
                ? nextChapter.startTime
                : details.duration ?? 0;
            }
          }
        }
      }
    }
  } catch {
    // Chapters parsing is best-effort
  }

  return {
    id: details.id ?? videoId,
    url: `https://www.youtube.com/watch?v=${details.id ?? videoId}`,
    title: details.title ?? '',
    description: details.short_description ?? '',
    duration: details.duration ?? 0,
    thumbnails: details.thumbnail
      ? mapThumbnails(details.thumbnail as unknown as Array<{ url: string; width: number; height: number }>)
      : [],
    channel: {
      id: details.channel_id ?? '',
      name: (details.author ?? '') as string,
      url: details.channel_id ? `https://www.youtube.com/channel/${details.channel_id}` : '',
      subscribers: null,
    },
    viewCount: details.view_count ?? 0,
    uploadDate: '',
    category: '',
    tags: (details.tags ?? []) as string[],
    isLive: details.is_live ?? false,
    isPrivate: details.is_private ?? false,
    formats: mapFormats(allFormats),
    subtitles,
    chapters,
  };
}

export async function getPlaylistInfo(urlOrId: string, options?: YtdlPlusOptions): Promise<PlaylistInfo> {
  const innertube = await getInnertube(options);
  const playlistId = extractPlaylistId(urlOrId) ?? urlOrId;

  const playlist = await innertube.getPlaylist(playlistId);

  const videos: PlaylistItem[] = [];
  const items = playlist.items ?? [];

  for (let i = 0; i < items.length; i++) {
    const item = items[i] as unknown as Record<string, unknown>;
    const videoId = (item['id'] as string) ?? '';
    const titleObj = item['title'] as Record<string, unknown> | string | undefined;
    const title = typeof titleObj === 'string' ? titleObj : (titleObj?.['text'] as string) ?? '';
    const durationObj = item['duration'] as Record<string, unknown> | undefined;
    const durationSec = (durationObj?.['seconds'] as number) ?? 0;
    const thumbnailsRaw = item['thumbnails'] as Array<{ url: string; width: number; height: number }> | undefined;
    const thumb = thumbnailsRaw?.[0] ?? null;
    const authorObj = item['author'] as Record<string, unknown> | undefined;

    videos.push({
      id: videoId,
      title,
      duration: durationSec,
      thumbnail: thumb ? { url: thumb.url, width: thumb.width, height: thumb.height } : null,
      channel: {
        name: (authorObj?.['name'] as string) ?? '',
        id: (authorObj?.['id'] as string) ?? '',
      },
      index: i,
    });
  }

  const headerInfo = playlist.info as unknown as Record<string, unknown>;

  return {
    id: playlistId,
    url: `https://www.youtube.com/playlist?list=${playlistId}`,
    title: (headerInfo?.title as string) ?? '',
    description: (headerInfo?.description as string) ?? '',
    channel: {
      name: (headerInfo?.author as string) ?? '',
      id: '',
      url: '',
    },
    videoCount: videos.length,
    thumbnails: [],
    videos,
  };
}
